# Generated by Django 3.2 on 2021-05-13 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=200)),
                ('pub_date', models.DateField()),
            ],
        ),
    ]
